export default {
    FETCH_PERSON_START: "FETCH_PERSON_START",
    FETCH_PERSON_SUCCESS: "FETCH_PERSON_SUCCESS",
    FETCH_PERSON_ERROR: "FETCH_PERSON_ERROR",

    FETCH_PERSON_CREDITS_START: "FETCH_PERSON_CREDITS_START",
    FETCH_PERSON_CREDITS_SUCCESS: "FETCH_PERSON_CREDITS_SUCCESS",
    FETCH_PERSON_CREDITS_ERROR: "FETCH_PERSON_CREDITS_ERROR",
}