export default {
    FETCH_MOVIE_START: "FETCH_MOVIE_START",
    FETCH_MOVIE_SUCCESS: "FETCH_MOVIE_SUCCESS",
    FETCH_MOVIE_ERROR: "FETCH_MOVIE_ERROR",

    FETCH_MOVIE_CREDITS_START: "FETCH_MOVIE_CREDITS_START",
    FETCH_MOVIE_CREDITS_SUCCESS: "FETCH_MOVIE_CREDITS_SUCCESS",
    FETCH_MOVIE_CREDITS_ERROR: "FETCH_MOVIE_CREDITS_ERROR",
}